services:
  - type: web
    name: intelligent-translation-tech-site
    runtime: static
    branch: main
    buildCommand: ""
    staticPublishPath: .
    previews:
      generation: automatic
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
